### ISSUE TITLE
Incorrect error raised when API Key is missing

### ISSUE THREAD

**Issue by johnc44** [LoginRadius/python-sdk#1]
If I create an instance of the LoginRadius class like this:

```
from LoginRadius import LoginRadius as LR
lr = LR()
```

Then I get an error: TypeError: __init__() missing 1 required positional argument: 'version'

This looks to be because the LoginRadius __init__.py is creating a "NoAPIKey" error without passing in the version into its init method.

Full traceback:

```
  File "/var/task/LoginRadius/__init__.py", line 70, in __init__
    raise Exceptions.NoAPIKey
TypeError: __init__() missing 1 required positional argument: 'version'
```

**Comment by Karl-LoginRadius** [comment]
Thanks for raising this concern, we will review and schedule a fix with our next SDK release. If you need assistance with the current version and handling these exceptions please reach out to LoginRadius support.

**Comment by divyhshah** [comment]
Hey can i take this issue?

**Comment by ashish8947** [comment]
Hello, @divyhshah  Thanks for your interest. Please feel free to raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by fumblehool** [comment]
@ashish8947 Can I work on it, if thats ok?

**Comment by sushrut111** [comment]
I do not see any pull request created for this, can I go ahead and work on this?

**Comment by sushrut111** [comment]
This is issue does not seem to be reproducible.

**Comment by Sudhanshu-Dubey14** [comment]
Right, this issue does not exist anymore and so it should be closed.

**Comment by giriraj12000** [comment]
Hi,

We are unable to replicate the issue and seems the issue is invalid so closing this thread

Thanks
