### ISSUE TITLE
Dependency not included in pip installation

### ISSUE THREAD

**Issue by 17sushmita** [LoginRadius/python-sdk#21]
## Bug
While installing the library using `pip install loginradius-v2==11.0.0` , dependencies doesn't get automatically downloaded with it. It needs to be installed manually.

**Comment by shreayan98c** [comment]
I would like to work on this issue. I'll create a new python environment and create a requirements.txt file containing all the dependencies.

**Comment by shreayan98c** [comment]
Fixed the issue and created PR #30 to address it.

**Comment by indrasen715** [comment]
Hi @17sushmita @shreayan98c  ,

Thanks for your contribution, we have included this  particular request  in our latest release version 11.2.0 

https://github.com/LoginRadius/python-sdk/releases/tag/11.2.0

Please feel free to share with us, if you see any other areas of improvement. 

Regards
Indrasen
