### ISSUE TITLE
Need update in Readme.md

### ISSUE THREAD

**Issue by simarpreetsingh-019** [LoginRadius/python-sdk#24]
Hi there, I just come across this project and was exploring the readme. 
I have few suggestions after reading the repo : 

- You have provided a lot of info, which is great, but jump to links in the readme is a demand which I think would give another edge as well as beautify the readability of this repo, saving a lot of time also. 

- I think the configuration part should come to the top because it is the first step while installing the program, which is provided at the end of repo at the moment. could save a lot of time while installing and doing the first run.

I would like to work on this issue.

**Comment by maskmanlucifer** [comment]
Hey ! i want to work on this issue can I go for it.

**Comment by vvHacker007** [comment]
The links are just too messy we can embed them inside a text can  you assign me this issue so that i can work on that

**Comment by simarpreetsingh-019** [comment]
@shubhneet182 , @tb-rules10 , I appreciate your work, but I created this issue so that I could work on this.

What will I do if you work on an issue which is not even reviewed yet, and was created and searched by someone else?

**Comment by shubhneet182** [comment]
@simarpreetsingh-019 I am not familiar with the GitHub platform much and thought that issues are mainly created by maintainers and can be solved by anyone. 

I apologize for not asking first whether anyone was working on the issue.

**Comment by simarpreetsingh-019** [comment]
No problem , keep it in mind for next time..

**Comment by giriraj12000** [comment]
Hi @simarpreetsingh-019 

Thanks for sharing the feedback. Please find the below answer for the raised query

* We already have the Jump to link feature for navigating to a particular section into our API docs.
* We have provided the demo configuration steps under the demo section so you can refer to this one.

Thanks
